### ISSUE TITLE
FCM Push notifications do not work on iOS 11

### ISSUE THREAD

**Issue by alexanderkhitev** [firebase/quickstart-ios#327]
I use Firebase as a backend. I also use FCM as one of the provided features from Firebase. FCM worked well in iOS 10, but after switching to iOS 11, push notifications stopped coming to user devices, and I myself did not receive any push notifications sent from the cloud functions or the Notification section in the Firebase Console. How to fix this problem?

  [1]: https://stackoverflow.com/questions/44796613/silent-pushes-not-delivered-to-the-app-on-ios-11

**Update:** I sent several push notifications from Firebase Notifcations, but they do not come.

    // MARK: - Push notification
    
    extension AppDelegate: UNUserNotificationCenterDelegate {
        
        func registerPushNotification(_ application: UIApplication) {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
                    
            // For iOS 10 data message (sent via FCM)
            Messaging.messaging().delegate = self
        }
        
        func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
            //When the notifications of this code worked well, there was not yet.
            Messaging.messaging().apnsToken = deviceToken
        }
        
        // [START receive_message]
        func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
            // If you are receiving a notification message while your app is in the background,
            // this callback will not be fired till the user taps on the notification launching the application.
            // TODO: Handle data of notification
            // Print message ID.
            if let messageID = userInfo[gcmMessageIDKey] {
                debugPrint("Message ID: \(messageID)")
            }
            
            // Print full message.
            debugPrint(userInfo)
        }
        
        func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                         fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
            // If you are receiving a notification message while your app is in the background,
            // this callback will not be fired till the user taps on the notification launching the application.
            // TODO: Handle data of notification
            // Print message ID.
            if let messageID = userInfo[gcmMessageIDKey] {
                print("Message ID: \(messageID)")
            }
            
            // Print full message.
            debugPrint(userInfo)
            
            completionHandler(.newData)
        }
        
        // showing push notification
        
        func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
            if let userInfo = response.notification.request.content.userInfo as? [String : Any] {
                let routerManager = RouterManager()
                routerManager.launchRouting(userInfo)
            }
            completionHandler()
        }
        
        func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
            if let userInfo = notification.request.content.userInfo as? [String : Any] {
                if let categoryID = userInfo["categoryID"] as? String {
                    if categoryID == RouterManager.Categories.newMessage.id {
                        if let currentConversation = ChatGeneralManager.shared.currentChatPersonalConversation, let dataID = userInfo["dataID"] as? String  {
                            // dataID is conversationd id for newMessage
                            if currentConversation.id == dataID {
                                completionHandler([])
                                return
                            }
                        }
                    }
                }
                if let badge = notification.request.content.badge {
                    AppBadgesManager.shared.pushNotificationHandler(userInfo, pushNotificationBadgeNumber: badge.intValue)
                }
            }
            completionHandler([.alert,.sound, .badge])
        }
        
    }
    
    // [START ios_10_data_message_handling]
    extension AppDelegate : MessagingDelegate {
        
        func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
            let pushNotificationManager = PushNotificationManager()
            pushNotificationManager.saveNotificationTokenInDatabase(token: fcmToken, success: nil, fail: nil)
        }
    
        
        // Receive data message on iOS 10 devices while app is in the foreground.
        func application(received remoteMessage: MessagingRemoteMessage) {
            debugPrint(remoteMessage.appData)
        }
        
    }

**Comment by caiovidaln** [comment]
I have the same problem.

**Comment by alexanderkhitev** [comment]
Hi @caiovidaln !
Please see my answer on my question https://stackoverflow.com/questions/46391818/fcm-push-notifications-do-not-work-on-ios-11 It helped me, I'm currently testing, so that everything works as before, but unfortunately it will be necessary to wait until Apple confirms the new Build.

**Comment by berlininsomniac** [comment]
We have the same issue. Once the app goes into the background, no pushes are received at all.

**Comment by visskiss** [comment]
Also not receiving push notifications with iOS 11 and latest firebaseMessaging  2.0.3, firebase 4.2.0.  I have used the apps.sh script to test and i receive those notifications, but using the fcm id and sending through the console and I receive nothing.

**Comment by ordinaryman09** [comment]
I noticed from your code, you're not running the request for push authorization from application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions, perhaps you call it at later time?

I have similar issue. I updated to Firebase 4.2.0 and FirebaseMessaging 2.0.3, my issue is I'm not getting notification if I do request push notification at later time. (I'm doing soft request/custom dialog to check if user want to receive push notification, before using the system request). I was able to reproduce it from the quickstart project by adding a delay to the requestAuthorization for push.  Here's my SO thread: https://stackoverflow.com/questions/46443189/firebase-messaging-not-sending-notification-when-push-notification-authenticatio

**Comment by rsattar** [comment]
There is a known issue where the FCM token is not always being associated with the APNs device token if `UIApplication.shared.registerForRemoteNotifications()` is not called early enough. This has  already been fixed in the FirebaseInstanceID SDK, and should be coming out soon.

In the meantime, you can:

1. Lock your `FirebaseInstanceID` pod to `2.0.0` in your Podfile, or

2. Ensure you're calling `UIApplication.shared.registerForRemoteNotifications()` on app start, ideally before `FirebaseApp.configure()`.

For testing, you can trigger a new FCM token by uninstall/reinstall your debug app on your device.

**Comment by ordinaryman09** [comment]
Got it. do you have any ETA when the version will be released?
Tried to lock it, setting pod 'FirebaseInstanceID', '~> 2.0.0' , but it kept using the 2.0.3, How do I downgrade it?

**Comment by jtbh89** [comment]
@rsattar Thanks so much! Locking FirebaseInstanceID to 2.0.0 worked for me.
@ordinaryman09 remove the arrow for an exact match: pod 'FirebaseInstanceID', '2.0.0'

**Comment by morganchen12** [comment]
@ordinaryman09 to specify exact versions, you should use `'= 2.0.0'`. CocoaPods' `~>` specifier will use the most recent compatible version.

**Comment by 10686142** [comment]
Both downgrading the FirebaseInstanceID and FirebaseMessaging and placing the UIApplication.shared.registerForRemoteNotifications() as the first thing in the didFinishLaunchingWithOptions still doesn't work and gives a similar error. Is there anything else I can do?

**Comment by rsattar** [comment]
@10686142 try uninstalling the app and reinstalling with the code changes, to ensure that a new FCM token gets issued

**Comment by 10686142** [comment]
Yeah somehow I still can't get it to work, but maybe I did something wrong since I am new to this.  But maybe someone knows what it can be: 
I followed this tutorial: https://www.youtube.com/watch?v=_jy_Hlskmiw&t=710s
Which came down to me delegate looking like this: https://github.com/douglasdevelops/PushNotificationSample/blob/master/PushNotificationSample/AppDelegate.swift

Is he maybe missing something is his explanation or am I missing something?

Thanks in advance!

**Comment by richardliveraise** [comment]
Thanks @jtbh89 & @rsattar , I downgraded to 2.0.0 and it works for me now. @10686142 what messages are you seeing? Do you get the tokens?

**Comment by 10686142** [comment]
2017-09-28 21:26:20.067218+0200 App Imperium News[1026:80671] [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
2017-09-28 21:27:05.337971+0200 App Imperium News[1026:80673] TIC Read Status [5:0x0]: 1:57
2017-09-28 21:27:05.338807+0200 App Imperium News[1026:80673] TIC Read Status [5:0x0]: 1:57

**Comment by 10686142** [comment]
Yeah I did also receive the token. And I got it to work earlier today that I could also see the message in me debug log, but I always get that message about FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Comment by 10686142** [comment]
I got it to work finally guys! I added this piece of code:
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
    }

**Comment by 10686142** [comment]
Beginners mistake I think, thanks for your help! @rsattar @richardliveraise

**Comment by ordinaryman09** [comment]
it works for me after downgrading to 2.0.0, thanks guys!

**Comment by candywriter** [comment]
**@rsattar** Without using CocoaPods, how is it possible to downgrade to 2.0.0 to fix this? Can you provide a link to download the working framework(s)?

**Comment by morganchen12** [comment]
@candywriter you can download the `tar.gz` from the link in the [2.0.0 podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/3/6/0/FirebaseInstanceID/2.0.0/FirebaseInstanceID.podspec.json#L21) without using CocoaPods.

https://dl.google.com/dl/cpdc/9fe91bfb8772be4b/FirebaseInstanceID-2.0.0.tar.gz

**Comment by candywriter** [comment]
@morganchen12 Thanks! Unfortunately manually replacing FirebaseInstanceID 2.0.3 with 2.0.0 produces a host of build errors.

**Comment by visskiss** [comment]
I had no issues. Are you on the latest download besides that?

**Comment by phr85** [comment]
Try to set this, works for me:

`        Messaging.messaging().shouldEstablishDirectChannel = true
`

**Comment by phr85** [comment]
Sorry, my memories solution isn't really the solution. Message just arrived when app is active.

**Comment by farazq** [comment]
Downgrading FirebaseInstanceID to 2.0.0 did not work for me either. 
However, adding this did work:
`Messaging.messaging().apnsToken = deviceToken`
 in _didRegisterForRemoteNotificationsWithDeviceToken_

I'm confused why it works because this is only supposed to be in place if you have swizzling disabled, which I don't.

**Comment by caiovidaln** [comment]
The solutions presented above did not work for me. I am using FirebaseInstanceID: 2.0.0, FirebaseMessaging: 2.0.0, FirebaseCore: 4.0.7, Firebase: 4.2.0 and FirebaseAnalytics: 4.0.3. Testing with iOS 11.

The message arrives with the application active, but it does not arrives when is in background.


    extension AppDelegate: UNUserNotificationCenterDelegate {
        // Receive displayed notifications for iOS 10 devices.
        func userNotificationCenter(_ center: UNUserNotificationCenter,
                                    willPresent notification: UNNotification,
                                    withCompletionHandler completionHandler:
            @escaping (UNNotificationPresentationOptions) -> Void) {
            completionHandler(.alert)
        }
        
        func userNotificationCenter(_ center: UNUserNotificationCenter,
                                    didReceive response: UNNotificationResponse,
                                    withCompletionHandler completionHandler: @escaping () -> Void) {
            completionHandler()
        }
        
        func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
            Messaging.messaging().apnsToken = deviceToken
        }

        
        func registerForPushNotifications(application: UIApplication) {
            
            FirebaseApp.configure()
            application.registerForRemoteNotifications()
            
            
            UNUserNotificationCenter.current().delegate = self
            
            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: {_, _ in })
            
            Messaging.messaging().delegate = self
        }
        
        func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
            print("Notification: Unable to register for remote notifications: \(error.localizedDescription)")
        }
        
        func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
            NotificationCenterController.processMessage(userInfo)
        }
        
        func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
            NotificationCenterController.processMessage(userInfo)
            completionHandler(.newData)
        }
        
        
    }

    extension AppDelegate: MessagingDelegate {
        func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
            print("Refresh Token")
        }
        
        
        // Receive data message on iOS 10 devices while app is in the foreground.
        func application(received remoteMessage: MessagingRemoteMessage) {
            NotificationCenterController.processMessage(remoteMessage.appData)
        }

    }

**Comment by royherma** [comment]
+1, using all new (Podfile.lock)
```
- Firebase/Core (4.2.0):
    - FirebaseAnalytics (= 4.0.3)
    - FirebaseCore (= 4.0.7)
  - Firebase/Database (4.2.0):
    - Firebase/Core
    - FirebaseDatabase (= 4.0.3)
  - Firebase/Messaging (4.2.0):
    - Firebase/Core
    - FirebaseMessaging (= 2.0.3)```

Confirmed able to get push by APNS directly, not able to get push from firebase api/notification panel.

**Comment by lsalvoni** [comment]
+1 to @farazq and overriding the swizzling method(s); even though I have set `FirebaseAppDelegateProxyEnabled` to `NO` in the Info.plist as the docs state, it seems to have no effect. (ie I am opting to NOT use method swizzling)

Using Cocoapods and FirebaseCore (4.0.7) FirebaseMessaging (2.0.3) for reference.

**Comment by royherma** [comment]
@lsalvoni I spent a few hours trying to understand wasn't working till i got to this thread.

The solution was moving my pods to this:

```
    pod 'Firebase/Core', '4.0.4'
    pod 'Firebase/Database', '4.0.4'
    pod 'Firebase/Messaging', '4.0.4'
    pod 'FirebaseInstanceID', '2.0.0'
```

**Comment by 0atme0** [comment]
@royherma 
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken  {
    [FIRMessaging messaging].APNSToken = deviceToken;

and have you implemented these methods?

**Comment by Kharauzov** [comment]
I just also met the same problem. O my got, I just spent 2 hours on nothing trying to fix the problem with the certificates and provision profiles. But the only solution, that worked for me too was to decrease 'FirebaseInstanceID' version to 2.0.0.  After this notifications started to deliver on my iOS device.

**Comment by rsattar** [comment]
Hey everyone, we released `FirebaseInstanceID 2.0.4` today, which should be resolving a lot of the issues related to notification delivery. Please update to that if you're still having trouble.

**Comment by xeneka** [comment]
Hi, I update to FirebaseInstanceID 2.0.4 but not working

**Comment by 0atme0** [comment]
The application shows push on ios 10 and 11.1, but on 11.0.1-11.0.2 it does not work.
Writes
Ignoring notification with no alert, sound or badge (*********): 4BD0-6F71
[**********] Not saving push notification 4BD0-6F71 to store [error = Error Domain = UNErrorDomain Code = 1401 "Notification has no user-facing content" UserInfo = {NSLocalizedDescription = Notification has no user- facing content}]

Pods:
Installing Firebase (4.3.0)
Installing FirebaseAnalytics (4.0.4)
Installing FirebaseCore (4.0.8)
Installing FirebaseInstanceID (2.0.4)
Installing FirebaseMessaging (2.0.4)

What's wrong?

**Comment by o15a3d4l11s2** [comment]
Not working for me too. Still not receiving the notifications :(

**Comment by xeneka** [comment]
I send notification with console of fireblade y with curl.  the old version of app receive notification



import UIKit
import Fabric
import Crashlytics
import UserNotifications
import FirebaseCore
import Firebase
import FirebaseMessaging

fileprivate let viewActionIdentifier = "VIEW_IDENTIFIER"
fileprivate let newsCategoryIdentifier = "NEWS_CATEGORY"


@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?


    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        Fabric.with([Crashlytics.self])
        UNUserNotificationCenter.current().delegate = self

        // Override point for customization after application launch.
        registerForPushNotifications()
        
        // 1
        if let notification = launchOptions?[.remoteNotification] as? [String: AnyObject] {
            // 2
            let aps = notification["aps"] as! [String: AnyObject]
            print(aps)
            //_ = NewsItem.makeNewsItem(aps)
            // 3
           // (window?.rootViewController as? UITabBarController)?.selectedIndex = 1
        }
        
      
        
        FirebaseApp.configure()
        connectToFcm()
        Fabric.with([Crashlytics.self])
       
        return true
    }

    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
        
        Messaging.messaging().disconnect()
        print("Disconnected from FCM.")
        
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }
    
    ////MARK: - Notification
    
    // ojo fastlane sigh --development para generar certificado de develop
    
    func application(_ application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        
       
        
        let tokenParts = deviceToken.map { data -> String in
            return String(format: "%02.2hhx", data)
        }
        
        let token = tokenParts.joined()
        print("Device Token: \(token)")
        
        let tokenFIR = Messaging.messaging().fcmToken
        print("FIER TOKEN \(tokenFIR) fin")
        
    }
    
    /*func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) {
    
        print(userInfo)
    }*/
    
    func application(
        _ application: UIApplication,
        didReceiveRemoteNotification userInfo: [AnyHashable : Any],
        fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
        
        let aps = userInfo["aps"] as! [String: AnyObject]
        
        if aps["content-available"] as? Int == 1 {
            /*let podcastStore = PodcastStore.sharedStore
            podcastStore.refreshItems { didLoadNewItems in
                completionHandler(didLoadNewItems ? .newData : .noData)
            }*/
        } else  {
            //_ = NewsItem.makeNewsItem(aps)
            completionHandler(.newData)
        }
    }
    
    
    
    func application(_ application: UIApplication,
                     didFailToRegisterForRemoteNotificationsWithError error: Error) {
        print("Failed to register: \(error)")
    }
    
    
    func registerForPushNotifications() {
        UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .sound, .badge]) {
            (granted, error) in
            print("Permission granted: \(granted)")
            
            guard granted else { return }
            
            let viewAction = UNNotificationAction(identifier: viewActionIdentifier,
                                                  title: "View",
                                                  options: [.foreground])
            
            let newsCategory = UNNotificationCategory(identifier: newsCategoryIdentifier,
                                                      actions: [viewAction],
                                                      intentIdentifiers: [],
                                                      options: [])
            
            UNUserNotificationCenter.current().setNotificationCategories([newsCategory])
            
            self.getNotificationSettings()
        }
    }
    
    func getNotificationSettings() {
        UNUserNotificationCenter.current().getNotificationSettings { (settings) in
            print("Notification settings: \(settings)")
            guard settings.authorizationStatus == .authorized else { return }
            DispatchQueue.main.async{
            UIApplication.shared.registerForRemoteNotifications()
            }
        }
    }
    
    // Firebase
    
    func connectToFcm() {
        
        
        Messaging.messaging().shouldEstablishDirectChannel = true
        Messaging.messaging().connect { (error) in
            if (error != nil) {
                print("Unable to connect with FCM. \(error ?? "Sin error" as! Error)")
            } else {
                print("Connected to FCM.")
            }
        }
    }
    
    
    //Init session y login and pass in keychain
    
    func loginWithKeychain() -> Bool{
        let keychainManager = userLoginKeychainManager()
        
        
        do {
            let user = try keychainManager.recoverData()
            if (!userManagerSession.getLogged()){
                userManagerSession.sharedInstance.initWithLogin(login: user)
            }
            return true
        }catch {
            print("User no register")
            return false
        }
        
        
        
    }
    
    


}


extension AppDelegate: UNUserNotificationCenterDelegate {
    
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        
        let userInfo = response.notification.request.content.userInfo
        let aps = userInfo["aps"] as! [String: AnyObject]
        
        /*if let newsItem = aps {
            (window?.rootViewController as? UITabBarController)?.selectedIndex = 1
            
            if response.actionIdentifier == viewActionIdentifier,
                let url = URL(string: newsItem.link) {
                //let safari = SFSafariViewController(url: url)
                //window?.rootViewController?.present(safari, animated: true, completion: nil)
            }
        }*/
        
        completionHandler()
    }
}

extension AppDelegate : MessagingDelegate {
    func messaging(_ messaging: Messaging, didRefreshRegistrationToken fcmToken: String) {
        print(messaging)
    }
    
    func messaging(_ messaging: Messaging, didReceive remoteMessage: MessagingRemoteMessage) {
        print("mesaje")
    }
    
    // Receive data message on iOS 10 devices.
    func application(received remoteMessage: MessagingRemoteMessage) {
        print("%@", remoteMessage.appData)
    }
}

**Comment by o15a3d4l11s2** [comment]
@rsattar I am sending notifications through https://console.firebase.google.com. If I target a specific FCM token the notification is sent, but sending to a User Segment -> App does nothing.

I register the token manually
```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    Messaging.messaging().apnsToken = deviceToken
}
```
but this does not help.

I have tried using `'FirebaseInstanceID', '2.0.0'` with no success.

I have also moved `UIApplication.shared.registerForRemoteNotifications()` on app start, before `FirebaseApp.configure()` with no success.

**Comment by whdinata** [comment]
Hi @rsattar,

I have exactly the same problem as what @o15a3d4l11s2 has. It would be great if we can hear from you soon.

**Comment by candywriter** [comment]
Agree with all of the other posters: upgrading to Firebase 4.3 (and more specifically FirebaseInstanceID 2.0.4) does not fix the broken push notifications on iOS. Really poor effort by the Firebase team.

**Comment by evollu** [comment]
@candywriter are you saying 2.0.0 works for you and upgrading to 2.0.4 made it fail again?

**Comment by keitaoouchi** [comment]
In iOS11.0, there seems to be a problem with iOS itself in handling silent push notification.
https://stackoverflow.com/questions/44796613/silent-pushes-not-delivered-to-the-app-on-ios-11

**Comment by o15a3d4l11s2** [comment]
@keitaoouchi I don't believe this is the reason for not receiving the notifications. They say this issue mentioned in StackOverflow is already fixed. Even if it is not - I experience a different issue - I always receive the push notifications when targeting a single device and very rarely receive notifications when sending to a User Segment.

**Comment by shintegu** [comment]
I'm also encountering the issue of @o15a3d4l11s2. I can receive push notifications by sending message to a single device, but almost nothing when using User Segment.

**Comment by eduardoParadoja** [comment]
I wasn't receiving any notifications until I deleted the .p12 files from the firebase console and upload the .p8 file [https://stackoverflow.com/questions/39672297/how-to-use-apples-new-p8-certificate-for-apns-in-firebase-console](https://stackoverflow.com/questions/39672297/how-to-use-apples-new-p8-certificate-for-apns-in-firebase-console.)

**Comment by o15a3d4l11s2** [comment]
@eduardoParadoja Thanks for the succession. I use APN Auth Key and not APN Push Certificate.

**Comment by jacobmoncur** [comment]
I am seeing the exact same issue as @o15a3d4l11s2. 

We are using the console (https://console.firebase.google.com) to send notifications. If I target an individual device using the FCM token the notification is received. If I try to send to a User Segment the notification is not received. :shrug: 

- We have the latests versions of the SDK installed. (`Firebase 4.3.0 , FirebaseAnalytics 4.0.4, FirebaseCore 4.0.8, FirebaseInstanceID 2.0.4, FirebaseMessaging 2.0.4`)
- We are using the APN Auth Key `.p8`
- We are calling `UIApplication.shared.registerForRemoteNotifications()` on app start in `didFinishLaunchingWithOptions` and before `FirebaseApp.configure()`

**Comment by amervil** [comment]
Exact the same issue as @jacobmoncur. Even same versions of Firebase, .p8, Xcode 9

**Comment by vincentsong** [comment]
Same issue as @jacobmoncur's. We need to ask user give permission to push notification after FirebaseApp configuration.

**Comment by ericklarac** [comment]
How do I use this solution?    fix is `pod 'FirebaseInstanceID', "2.0.0"`   

HELP, PLEASE.

**Comment by ordinaryman09** [comment]
@ericklarac You add it on your Podfile

**Comment by dhorrock** [comment]
**Pods:**
 pod 'Firebase/Core', '4.0.4'
 pod 'Firebase/Database', '4.0.4'
 pod 'Firebase/Messaging', '4.0.4'
 pod 'FirebaseInstanceID', '2.0.0'

**Getting**
2017-10-11 00:45:28.181 Customer Connect[1964] <Warning> [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

Any suggestions?

**Comment by lsalvoni** [comment]
@dhorrock You need to subscribe to the `FIRMessagingDelegate` and add the missing delegate method; see sample code in the AppDelegate.m of the MessagingExample project for your language of choice.

**Comment by raghuyt** [comment]
Hi all am also facing same problem ,but am not installed plugin coco pod on ios ,installed only "cordova-plugin-fcm" and done FCM setting its working all IOS Expect 11. am able to get token id also, sending notification  through API getting successful responses also ,but notification not coming IOS 11 but 10 its coming

**Comment by kerimsari** [comment]
Can not get it to work  either same problem with @o15a3d4l11s2.

**Comment by ericklarac** [comment]
@kerimsari @raghuyt @dhorrock 
What I did was:

1.  I opened terminal on the folder of the project, deleted the Podfile.lock.

2. Then exec pod install, with the following pods on Podfile:
      - pod 'Firebase/Core'
      - pod 'Firebase/Messaging'
      - pod 'FirebaseInstanceID', "2.0.0"

3.  Then I reviewed the certificates.

4. Run the project.

Note: If you are facing problems and you don't find a solution, I recommend you to start a new project and review each step. You can use the quickstart-ios [example](https://github.com/firebase/quickstart-ios) of firebase or this [example](https://www.appcoda.com/firebase-push-notifications/) which I found it awesome.

**Comment by raghuyt** [comment]
Hi @ericklarac  

How can i install this for cordova apps

pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'FirebaseInstanceID', "2.0.0"

Please can you help me with this .

**Comment by kerimsari** [comment]
Hi @ericklarac 

I've done what you said and i can send notifications via **topic target** but not to user segment..

Please suggest

**Comment by ericklarac** [comment]
@raghuyt  Open up Terminal on the folder of the project then edit the Podfile, you can use nano or vi  and just paste those lines (i.e. mine looks like this):

![image](https://user-images.githubusercontent.com/8422946/31500799-0f52279c-af2e-11e7-8c64-f48d3e3c56f7.png)

Then you save it and run the command: pod install, open the .xcworkspace with Xcode, run the project and you are done.

@kerimsari  If the notifications status on the firebase consoles is completed, click the notification and look the chart if sent is 0 it's because firebase isn't storing the tokens. Actually, I don't know how user segment works on the firebase console at all, but hope I could work.

**Comment by raghuyt** [comment]
@ericklarac  thank you now its working in all IOS versions ,till now IOS version 11.0.2 its working all devices
what i made changes is this
updated our cordova to new version and platform IOS to new version

**Comment by Dragna** [comment]
I had the same problem on my phone and solved it by restarting the phone, I was receiving the push after that. I hope it Wille be the same for you.

**Comment by ordinaryman09** [comment]
Firebase released a new update, anybody tested the new one?

**Comment by shihochan** [comment]
I have a problem don't receive push notification on my some devices.

Environment: 
- Xcode9
- Swift4

Devices:
iPhone6S Plus　(9.3.2)
iPhone5S　(10.3.2)
iPad Pro　(10.2.1)
iPhone7 Plus　(10.2.1)

In my Podfile.lock:
```
  - Firebase/Core (4.3.0):
  - Firebase/Messaging (4.3.0):
    - FirebaseMessaging (= 2.0.4)
  - FirebaseInstanceID (2.0.4)
```

Did v4.0.4~ really fix push problem??

**Comment by ericklarac** [comment]
Are you uploading the apple certificates (.p12 files) to firebase?

**Comment by kroikie** [comment]
@shihochan It may be useful to create a new issue since this one is closed. There are different ways in which messages should be handled between iOS 9 and 10 so that could be an issue but a new issue with more detail of your setup and how you are sending the message would be helpful.

**Comment by chliangGoogle** [comment]
Agree with @kroikie Looks like this thread has been involved with many off-topic issues. If your issue is different than what's on the title (that's been closed), please file a new issue and we will look into each individual one. Thanks!
